# Generated by Django 3.1.7 on 2021-04-23 18:25

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('driver_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('phone_number', models.IntegerField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('meal_id', models.AutoField(primary_key=True, serialize=False)),
                ('meal_name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='MenuCategories',
            fields=[
                ('category_id', models.AutoField(primary_key=True, serialize=False)),
                ('category_name', models.CharField(max_length=30, unique=True)),
                ('category_price', models.DecimalField(decimal_places=2, max_digits=4)),
                ('the_term_of_validity_days', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')])),
            ],
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0)),
                ('delivery_date', models.DateField(default=datetime.date(2021, 4, 23))),
                ('the_term_of_validity', models.DateField(default=datetime.date(2021, 4, 23))),
                ('meal_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='systemAPP.menu')),
            ],
        ),
        migrations.AddField(
            model_name='menu',
            name='meal_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='systemAPP.menucategories'),
        ),
    ]
