# Generated by Django 3.1.7 on 2021-05-13 15:21

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('delivery_ID', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
                ('delivery_date', models.DateField(default=datetime.date(2021, 5, 13))),
            ],
            options={
                'verbose_name': 'Dostawa',
                'verbose_name_plural': 'Dostawy',
            },
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('driver_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('phone_number', models.IntegerField(unique=True)),
            ],
            options={
                'verbose_name': 'Kierowca',
                'verbose_name_plural': 'Kierowcy',
            },
        ),
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('meal_name', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
            ],
            options={
                'verbose_name': 'Posiłek',
                'verbose_name_plural': 'Posiłki',
            },
        ),
        migrations.CreateModel(
            name='MealCategories',
            fields=[
                ('category_id', models.AutoField(primary_key=True, serialize=False)),
                ('category_name', models.CharField(max_length=30, unique=True)),
                ('category_price', models.DecimalField(decimal_places=2, max_digits=4)),
                ('the_term_of_validity_days', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')])),
            ],
            options={
                'verbose_name': 'Kategoria Posiłku',
                'verbose_name_plural': 'Kategorie Posiłków',
            },
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0)),
                ('the_term_of_validity', models.DateField(default=datetime.date(2021, 5, 13))),
                ('delivery_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='systemAPP.delivery')),
                ('meal_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='systemAPP.meal')),
            ],
            options={
                'verbose_name': 'Magazyn',
                'verbose_name_plural': 'Magazyn',
                'unique_together': {('delivery_ID', 'meal_name')},
            },
        ),
        migrations.AddField(
            model_name='meal',
            name='meal_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='systemAPP.mealcategories'),
        ),
        migrations.AddField(
            model_name='delivery',
            name='meal_name',
            field=models.ManyToManyField(through='systemAPP.Warehouse', to='systemAPP.Meal'),
        ),
    ]
