# Generated by Django 3.1.7 on 2021-04-11 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systemAPP', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menucategories',
            name='category_price',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
    ]
