# Generated by Django 3.1.7 on 2021-04-11 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systemAPP', '0002_auto_20210411_1352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='phone_number',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='menu',
            name='meal_name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='menucategories',
            name='category_name',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
